events {}

http {
  server {
    listen 80;
    server_name kapi.tojest.dev localhost;

    location /api/ {
      proxy_pass http://fastapi:8000/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
      proxy_pass http://react-app:80;
      proxy_set_header Host $host;
      proxy_http_version 1.1;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }
  }
}
