-- 013_migrate_notion_lessons.sql
-- Migracja treści lekcji z Notion do Supabase
-- Wygenerowano: 2026-04-07

DO $$
DECLARE
  v_path_wspolna uuid;
  v_path_nocode uuid;
  v_path_kod uuid;
  v_course_wspolna uuid;
  v_course_nocode uuid;
  v_course_kod uuid;
  v_lesson_id uuid;
BEGIN

SELECT id INTO v_path_wspolna FROM public.paths WHERE slug = 'wspolna';
SELECT id INTO v_path_nocode FROM public.paths WHERE slug = 'no_code';
SELECT id INTO v_path_kod FROM public.paths WHERE slug = 'kod';

DELETE FROM public.courses WHERE path_id IN (v_path_wspolna, v_path_nocode, v_path_kod);

INSERT INTO public.courses (path_id, title, "order")
VALUES (v_path_wspolna, 'Kurs AI – Ścieżka Wspólna', 1)
RETURNING id INTO v_course_wspolna;

INSERT INTO public.courses (path_id, title, "order")
VALUES (v_path_nocode, 'Kurs AI – Ścieżka No-Code', 1)
RETURNING id INTO v_course_nocode;

INSERT INTO public.courses (path_id, title, "order")
VALUES (v_path_kod, 'Kurs AI – Ścieżka B – Kod', 1)
RETURNING id INTO v_course_kod;

-- ============================================================
-- ŚCIEŻKA WSPÓLNA (mode=''single'')
-- ============================================================

-- Lesson 1: Wstęp
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_wspolna, 'Wstęp', 1, '8 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'single', 1, '[{"kind":"hero","text":"Po tej lekcji rozumiesz, w jakiej fazie rozwoju AI jesteśmy — i dlaczego to jest dokładnie ten moment, żeby wsiąść do pociągu"}]'),
(v_lesson_id, 'single', 2, '[{"kind":"markdown","content":"## Scena 1 — Skąd to wszystko się wzięło?\n\nWyobraź sobie, że historia AI to historia motoryzacji.\n\nRok 2022. OpenAI wypuszcza ChatGPT. To jak wynalezienie **samochodu parowego** — hałasuje, dymi, jedzie 15 km/h, ale wszyscy są zachwyceni, że w ogóle jedzie. Ludzie pytają Chata o przepis na jajecznicę i piszą o tym artykuły w gazetach."}]'),
(v_lesson_id, 'single', 3, '[{"kind":"markdown","content":"## Scena 2 — Ewolucja nastąpiła szybko\n\nMinął rok. Potem drugi. Modele zaczęły się mnożyć jak króliki — Google, Anthropic, Meta, Mistral, chińskie ekipy. Każdy chciał swój kawałek tortu.\n\nJak byś określił AI z 2023–2024? Pewnie jakiś solidny **Volkswagen Passat** — niezawodny, jeździ wszędzie, robi co trzeba. Może nawet **BMW serii 5** — już trochę elegancki, ma asystenta pasa ruchu i sam parkuje.\n\nAle to jeszcze nie był koniec."}]'),
(v_lesson_id, 'single', 4, '[{"kind":"markdown","content":"## Scena 3 — Gdzie jesteśmy TERAZ (2026)\n\nOto brutalna prawda: **tylko w ciągu ostatnich 3 miesięcy**, sama firma Anthropic wypuściła ponad 60 aktualizacji, poprawek i nowych funkcji. Dosłownie 60. To więcej niż większość firm technologicznych robi przez rok.\n\nKonkurencja? Też nie śpi. Google, OpenAI, xAI, DeepSeek — wszyscy jadą z gazem do dechy.\n\nJesteśmy teraz w erze **Bugatti jadącego 400 km/h**.\n\nI tu pojawia się ważne pytanie: czy chcesz stać przy drodze i machać ręką? Czy wsiąść?"}]'),
(v_lesson_id, 'single', 5, '[{"kind":"markdown","content":"## Scena 4 — Dokąd to zmierza?\n\nAI to już nie tylko „chatbot co pisze maile". To:\n\n- 🤖 **Roboty** sterowane głosem i obrazem\n- 🎧 **Asystenci offline** w Twoim telefonie (bez internetu!)\n- 📹 **Analiza kamer** w sklepach, kawiarniach, fabrykach\n- 🎭 **Deepfake** — zarówno jako zagrożenie, jak i narzędzie kreatywne\n- 🏥 Diagnozowanie chorób szybciej niż lekarz\n- ✍️ Kod piszący sam siebie\n\nI to wszystko **dzieje się teraz** — nie za 10 lat."}]'),
(v_lesson_id, 'single', 6, '[{"kind":"markdown","content":"## Scena 5 — Co możesz, a czego nie możesz wysyłać do AI\n\nJeden z najczęstszych błędów początkujących: wklejają do Claude''a / ChatGPT dane, których nie powinni wklejać.\n\n**Kategoria 1 — STOP (nigdy do chmurowego AI):**\n- Dane osobowe klientów (imiona, adresy, PESEL, numery kart) — RODO mówi: nie\n- Hasła, klucze API, tokeny dostępu\n- Umowy z klauzulą poufności które tego zabraniają\n\n**Kategoria 2 — OSTROŻNIE (sprawdź warunki):**\n- Dane finansowe firmy (przychody, marże)\n- Dane pracowników\n- Plany produktowe które są tajemnicą firmy\n\n**Kategoria 3 — BEZPIECZNE:**\n- Zadania bez danych osobowych\n- Kod który nie zawiera kluczy ani danych produkcyjnych\n- Dokumenty publiczne"}]'),
(v_lesson_id, 'single', 7, '[{"kind":"tip","title":"💡 Praktyczna rada","desc":"Zanim wkleisz cokolwiek do AI — zapytaj się: czy pokazałbym to komuś obcemu? Jeśli nie — użyj modelu lokalnego lub zanonimizuj dane.\n\nRozwiązanie dla danych wrażliwych: LM Studio + model lokalny. 100% prywatne, zero chmury."}]'),
(v_lesson_id, 'single', 8, '[{"kind":"tip","title":"Podsumowanie","desc":"Twój cel na ten kurs? Zostać jedną z tych osób, które nie tylko zauważyły — ale już korzystają z tej technologii lepiej niż 99% ludzi wokół.\n\nGotowy?"}]');

-- Lesson 2: Sztuka i inżynieria Promptowania
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_wspolna, 'Sztuka i inżynieria Promptowania', 2, '15 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'single', 1, '[{"kind":"hero","text":"Po tej lekcji przestajesz mówić do AI jak do magicznej kuli — i zaczynasz pisać prompty jak inżynier. Mniej magii, więcej wyników."}]'),
(v_lesson_id, 'single', 2, '[{"kind":"markdown","content":"## Scena 1 — Zaklinanie vs. Inżynieria\n\nWiększość ludzi pisze prompty tak:\n\n> *„Napisz mi coś o AI."*\n\nA potem dziwią się, że dostają ogólny tekst, który mógłby napisać student na kolokwium o 2 w nocy.\n\nSekret? W 2026 roku **dobre promptowanie to inżynieria kontekstu**, nie zaklinanie. Nie chodzi o magiczne słowa. Chodzi o to, żeby model DOKŁADNIE wiedział: kim jest, z kim rozmawia, co ma zrobić i czego mu NIE wolno robić."}]'),
(v_lesson_id, 'single', 3, '[{"kind":"code","language":"text","label":"Prompt C-O-R-E — przykład (przed i po)","code":"❌ ZŁY PROMPT:\n\"Napisz posta o AI w obsłudze klienta.\"\n\n✅ DOBRY PROMPT (C-O-R-E):\nContext: Jesteś ekspertem od automatyzacji piszącym dla właścicieli małych firm e-commerce (5–20 pracowników) w Polsce.\nObjective: Napisz posta LinkedIn który pokaże KONKRETNĄ liczbę — ile czasu/pieniędzy firma oszczędza na obsłudze klienta dzięki AI.\nRules: Max 1000 znaków. Zacznij od liczby lub pytania. Nie używaj słów: rewolucja, innowacja, przełom.\nExamples: \"Moja klientka odbierała 80 maili dziennie. Teraz AI odpowiada na 60 z nich. Wróciła do domu o 16:00.\""}]'),
(v_lesson_id, 'single', 4, '[{"kind":"framework","title":"Framework C-O-R-E","subtitle":"Twój szablon na całe życie. Zapamiętaj ten skrót. Używaj go za każdym razem.","items":[{"letter":"C","name":"Context (Kontekst)","desc":"Kim jest model? Z kim rozmawia? Jaki jest cel?","bad":"Napisz post na LinkedIn o AI.","good":"Jesteś ekspertem od automatyzacji. Piszesz do właścicieli małych firm, którzy boją się technologii. Pokaż, że AI oszczędza 2h dziennie.","color":"var(--cyan)"},{"letter":"O","name":"Objective (Cel)","desc":"Jeden jasny wynik. Używaj czasowników: Wygeneruj, Przeanalizuj, Skróć, Porównaj. Definiuj co dokładnie ma powstać.","bad":"","good":"Wygeneruj listę 5 konkretnych narzędzi no-code z linkami.","color":"#a78bfa"},{"letter":"R","name":"Rules (Zasady)","desc":"Czego modelowi NIE wolno? To Twoje zabezpieczenia przed bullshitem.","bad":"","good":"Nie używaj słów: rewolucyjny, niesamowity, przełomowy. Max 150 słów. Tylko po polsku, styl techniczny.","color":"var(--amber)"},{"letter":"E","name":"Examples (Przykłady)","desc":"Pokaż 2-3 przykłady Input → Output. To najskuteczniejszy trick w całym promptowaniu. Model naśladuje wzorzec — nie wymyśla go.","bad":"","good":"","color":"#34d399"}]}]'),
(v_lesson_id, 'single', 5, '[{"kind":"markdown","content":"## Scena 3 — Chain-of-Thought, czyli „myśl głośno"\n\nChcesz, żeby model nie strzelał odpowiedzi z biodra? Każ mu myśleć na głos przed odpowiedzią:\n\n> *„Przeanalizuj problem krok po kroku wewnątrz tagów `<thinking>`, zanim podasz wynik."*\n\nTo jak poproszenie pracownika, żeby najpierw pokazał swoje obliczenia zamiast od razu rzucać liczbą. Dramatycznie zmniejsza halucynacje."}]'),
(v_lesson_id, 'single', 6, '[{"kind":"markdown","content":"## Scena 4 — Biblioteka promptów\n\nNajlepsi użytkownicy AI nie piszą promptów od zera za każdym razem. Mają **bibliotekę szablonów** — gotowych schematów do: pisania maili, analizy danych, tworzenia postów, generowania kodu.\n\n## Scena 5 — System Prompt: instrukcja obsługi Twojego agenta\n\n**System prompt** to instrukcja która działa w tle — zanim użytkownik napisze cokolwiek. Model czyta ją przed każdą wiadomością i wie: kim jest, z kim rozmawia, jakich zasad przestrzega.\n\nGdzie to ustawić:\n- **Claude Projects:** Otwórz projekt → Instrukcje projektu → wpisz system prompt\n- **Claude API:** Pole `system` w każdym requeście\n- **n8n / Agenty:** Pierwszy węzeł z System Message przed właściwym promptem"}]'),
(v_lesson_id, 'single', 7, '[{"kind":"code","language":"text","label":"Przykład system promptu dla asystenta copywritera","code":"Jesteś doświadczonym copywriterem specjalizującym się w polskim rynku B2B.\nPiszesz dla właścicieli małych firm (10–50 pracowników), którzy boją się technologii.\nTwój ton: konkretny, przyjazny, bez żargonu. Maksymalna długość posta: 1200 znaków.\nNigdy nie używasz słów: rewolucyjny, innowacyjny, przełomowy, game-changer.\nGdy jesteś proszony o post — zawsze piszesz 3 warianty: formalny, casualowy i storytellingowy."}]'),
(v_lesson_id, 'single', 8, '[{"kind":"table","headers":["Zadanie","Temperatura"],"rows":[["Ekstrakcja danych z tekstu","0"],["Klasyfikacja / tagowanie","0"],["Generowanie kodu","0–0.2"],["Odpowiedzi na pytania z dokumentów","0.2–0.4"],["Pisanie maili / postów","0.5–0.7"],["Brainstorming / kreatywne pisanie","0.8–1.0"],["Generowanie wariantów reklam","1.0+"]]}]'),
(v_lesson_id, 'single', 9, '[{"kind":"tip","title":"Podsumowanie","desc":"Prompt = Brief dla kreatywnego pracownika. Im lepszy brief, tym lepszy wynik. Śmieciowy input = Śmieciowy output. To prawo nienaruszalne.\n\nGolden rule: dobry system prompt = model który nie pyta o rzeczy oczywiste i nie popełnia przewidywalnych błędów. Raz napisany, używany tysiąc razy."}]');

-- Lesson 3: Twój nowy zespół – modele webowe
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_wspolna, 'Twój nowy zespół – modele webowe', 3, '12 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'single', 1, '[{"kind":"hero","text":"Po tej lekcji wiesz, że nie musisz szukać jednego idealnego modelu. Zamiast tego budujesz drużynę superbohaterów. I wiesz, kogo wezwać na którą misję."}]'),
(v_lesson_id, 'single', 2, '[{"kind":"markdown","content":"## Scena 1 — Wyobraź sobie, że masz biuro pełne specjalistów\n\nWchodzisz rano do pracy. Przy biurku siedzą:\n\n- **Claude** — spokojny architekt z kubkiem kawy. Logiczny, precyzyjny, nie leje wody. Jakbyś zatrudnił doktora filozofii który też umie w kod.\n- **Gemini** — ten energiczny gość przy trzech monitorach. Ogląda wideo, analizuje zdjęcia, przetwarza dane z gigantycznych plików — wszystko naraz. Ma największy mózg w biurze.\n- **NotebookLM** — bibliotekarz z doskonałą pamięcią. Dajesz mu swoje notatki, PDFy, artykuły — a on zawsze cytuje dokładnie to co mu dałeś. Nigdy nic nie zmyśla.\n- **Grok** — reporter z X (Twitter). Zawsze wie co się dzieje *teraz*, pisze jak człowiek i ma lekkie pióro.\n\nTwoja robota? Wiedzieć, do kogo iść z jakim zadaniem."}]'),
(v_lesson_id, 'single', 3, '[{"kind":"table","headers":["Model","Supermoc","Kiedy go wołasz?"],"rows":[["Claude","Logika, kod, struktury","Strategia, refaktoryzacja, długie dokumenty"],["Gemini","Multimoda, gigantyczny kontekst","Analiza wideo/zdjęć, ogromne bazy danych"],["NotebookLM","Zero halucynacji na Twoich źródłach","Nauka z PDFów, podcasty z notatek"],["Grok","Real-time dane + ludzki język","Trendy, copywriting, social media"]]}]'),
(v_lesson_id, 'single', 4, '[{"kind":"markdown","content":"## Scena 3 — Workflow, który robi robotę\n\n**Przykład No-Code (content creator):**\n1. Sprawdź trendy na **Grok** → „Co teraz hype''uje w AI?"\n2. Wrzuć artykuły do **NotebookLM** → Zrób podsumowanie bez bullshitu\n3. Wyślij do **Claude** → Napisz strategię posta\n4. Wygeneruj grafikę w **Canva AI** → Gotowe!\n\n**Przykład dla dewelopera:**\n1. Opisz nową funkcję w **Claude Projects** → Dostajesz architekturę: jakie endpointy, jaka baza, jaki schemat danych\n2. Wklej schemat do **Gemini IDE** → Generuje boilerplate, pisze migracje SQL, obsługuje całą warstwę backendu"}]'),
(v_lesson_id, 'single', 5, '[{"kind":"table","headers":["Sytuacja","Narzędzie","Dlaczego?","Koszt"],"rows":[["Mam długi PDF i chcę zadawać pytania","NotebookLM","Zero halucynacji, cytuje źródła","Darmowe"],["Piszę kod / restrukturyzuję projekt","Claude Pro + Claude Code","Najlepsza jakość rozumowania i kodu","~20$/mc"],["Mam plik wideo / obraz / ogromny plik","Gemini Pro","Największy kontekst, multimodal","~20$/mc"],["Chcę wiedzieć co się dzieje TERAZ","Grok (X Premium)","Real-time dane z X/internetu","~8$/mc"],["Chcę automatyzować bez kodu","n8n (cloud)","Wizualny workflow, 200+ integracji","0–20$/mc"],["Mam dane firmowe i nie mogę ich wysyłać do chmury","LM Studio + model lokalny","100% prywatne, zero internetu","Jednorazowo: darmowe"]]}]'),
(v_lesson_id, 'single', 6, '[{"kind":"tip","title":"Złota zasada","desc":"Żaden model nie jest najlepszy. Najlepszy to ten właściwy do zadania. Mieszaj je świadomie — to jest supermoc 2026 roku.\n\nNajlepszy model to nie ten najmądrzejszy, to ten właściwy do zadania. Budowanie nawyku przeskakiwania między modelami to jedna z ważniejszych umiejętności 2026 roku."}]');

-- Lesson 4: Baza narzędzi
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_wspolna, 'Baza narzędzi', 4, '10 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'single', 1, '[{"kind":"hero","text":"Po tej lekcji nie masz listy narzędzi w głowie — masz przepisy. Wiesz co otworzyć gdy masz konkretny problem."}]'),
(v_lesson_id, 'single', 2, '[{"kind":"markdown","content":"## Scena 1 — Anty-przykład: syndrom zbierania narzędzi\n\nZnasz tego człowieka? Ma 15 zakładek otwartych jednocześnie: Claude, ChatGPT, Perplexity, Gemini, NotebookLM, Midjourney... I pyta na każdym czacie to samo, bo „może tutaj wyjdzie lepiej".\n\nTo nie jest produktywność. To kolekcjonowanie.\n\nPrzepis to coś innego: **konkretna sytuacja → konkretne narzędzie → konkretny wynik**. Żadnych zbędnych kroków."}]'),
(v_lesson_id, 'single', 3, '[{"kind":"markdown","content":"## Scena 2 — Przepisy 1–4\n\n### 📄 Przepis 1: Duży PDF → NotebookLM\nWrzuć do NotebookLM → zadawaj pytania → pobierz podcast-podsumowanie. Nie hallucynuje, cytuje dokładnie Twoje dokumenty.\n\n### 🔒 Przepis 2: Dane firmowe / prywatność → LM Studio\nPobierz LM Studio → wybierz model (Llama 3.1) → uruchom lokalnie. 100% prywatne, zero internetu.\n\n### 💻 Przepis 3: Piszesz kod → Claude Pro + Claude Code\nTerminal w folderze projektu → `claude` → rozmawiaj jak z seniorem. Widzi całe repo, iteruje, uruchamia komendy.\n\n### 📹 Przepis 4: Wideo / obraz do analizy → Gemini Pro\nWrzuć plik do Gemini → opisz co chcesz wiedzieć. Największy kontekst (2M tokenów), multimodalny."}]'),
(v_lesson_id, 'single', 4, '[{"kind":"markdown","content":"## Scena 2 — Przepisy 5–8\n\n### ⚙️ Przepis 5: Automatyzacja powtarzalnych zadań → n8n\nZbuduj workflow z węzłów (trigger → akcja → akcja) → aktywuj → zapomnij. Self-hosted n8n jest darmowy.\n\n### 📡 Przepis 6: Co się dzieje w internecie TERAZ → Grok\nOtwórz Grok → zapytaj. Real-time dane z X i wyszukiwarki. Wymaga X Premium (~8$/mc).\n\n### 📝 Przepis 7: Wiedza projektowa → Pliki .md + Claude Projects\nUtwórz folder z plikami .md → wrzuć do Claude Projects → każda sesja ma kontekst.\n\n### 🔍 Przepis 8: AI na Twoich danych → RAG z bazą wektorową\nWektoryzuj dokumenty (LlamaIndex / Chroma) → zbuduj endpoint → podepnij do interfejsu. Jeśli nie piszesz kodu: Dify.ai lub Flowise."}]'),
(v_lesson_id, 'single', 5, '[{"kind":"markdown","content":"## Scena 3 — Kiedy wybrać złe narzędzie (anty-przykłady)\n\n**Błąd 1:** Wrzucasz 50-stronicowy kontrakt do Claude.ai i dostajesz ogólną odpowiedź. Claude widzi tylko fragment. Prawidłowo: **NotebookLM albo Gemini Pro**.\n\n**Błąd 2:** Budujesz prostą automatyzację (\"wyślij maila gdy pojawi się nowy lead\") w Pythonie od zera. 3 godziny kodu. Prawidłowo: **n8n, 15 minut, zero kodu**.\n\n**Błąd 3:** Używasz LM Studio do codziennego pisania maili i narzekasz że model jest słaby. Prawidłowo: **LM Studio do prywatnych danych, Claude do codziennej pracy**."}]'),
(v_lesson_id, 'single', 6, '[{"kind":"tip","title":"Podsumowanie","desc":"Najlepsze narzędzie to nie to z największą liczbą funkcji — to to które rozwiązuje Twój konkretny problem bez zbędnego kombinowania.\n\n**Zadanie:** Weź 3 powtarzalne zadania które robisz co tydzień. Dopasuj każde do przepisu. Wdróż choć jedno."}]');

-- ============================================================
-- ŚCIEŻKA NO-CODE (mode=''technical'')
-- ============================================================

-- Lesson 1: Zarządzanie wiedzą (pliki .md)
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_nocode, 'Zarządzanie wiedzą (pliki .md)', 1, '10 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Nauczysz się tworzyć i organizować pliki Markdown jako bazę wiedzy — tak żeby twoje agenty AI zawsze wiedziały, co mają wiedzieć, bez konieczności tłumaczenia tego od nowa przy każdej rozmowie."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Problem z wiedzą w głowie\n\nWyobraź sobie, że zatrudniasz nowego pracownika. Jest zdolny, szybki, chętny do pracy. Ale za każdym razem gdy przychodzi do biura — nie pamięta niczego z poprzedniego dnia. Musisz tłumaczyć mu od nowa, jak działa firma, jakie są zasady, kim jest klient.\n\nBrzmi frustrująco? Dokładnie tak działa model AI bez bazy wiedzy.\n\nKażda rozmowa zaczyna się od zera. Agent nie wie, kim jesteś, co budujesz, jakich zasad się trzymasz. Chyba że mu to powiesz. A najlepiej — zapiszesz mu to raz, w pliku, który zawsze dostaje na początku.\n\nI właśnie do tego służą pliki `.md`."}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"markdown","content":"## Scena 2 — Czym jest Markdown i dlaczego AI go kocha\n\n**Markdown** to lekki format tekstowy do pisania sformatowanych dokumentów. Zamiast klikać „pogrub" w Wordzie, piszesz `**tekst**`. Zamiast klikać nagłówek — piszesz `# Nagłówek`.\n\nPlik `.md` to zwykły plik tekstowy. Otworzysz go w Notatniku, w VS Code, w Obsidianie — wszędzie.\n\nDlaczego AI go uwielbia:\n- **Czysty tekst** — żadnych binarnych formatów, zero problemów z odczytem\n- **Struktura przez nagłówki** — model od razu rozumie hierarchię informacji\n- **Lekki** — jeden plik `.md` z instrukcjami zajmuje kilka KB, nie MB\n- **Wszechobecny** — GitHub, Notion, Claude, Gemini — wszystkie rozumieją Markdown natywnie"}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"code","language":"markdown","label":"Przykład pliku firma.md","code":"# O firmie\nTworzymy aplikacje webowe dla małych firm z branży HoReCa.\n\n## Ton komunikacji\nPrzyjazny, bezpośredni. Bez korporacyjnego żargonu.\n\n## Klienci\nWłaściciele restauracji i hoteli, 30–55 lat, niekoniecznie techniczni."}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"markdown","content":"## Scena 3 — Jak strukturyzować pliki wiedzy\n\nNie ma jednego słusznego sposobu, ale jest kilka sprawdzonych wzorców:\n\n**Jeden plik na kontekst** — zamiast jednego gigantycznego pliku `wszystko.md`, tworzysz mniejsze, tematyczne:\n- `firma.md` — misja, wartości, ton komunikacji\n- `produkty.md` — opis oferty, ceny, najczęstsze pytania\n- `klient_X.md` — notatki o konkretnym kliencie\n- `instrukcje_agenta.md` — jak agent ma się zachowywać\n\n**Nagłówki jako nawigacja** — używaj `#`, `##`, `###` żeby tworzyć hierarchię.\n\n**Konkretne zamiast ogólnych** — zamiast „piszemy przyjazne maile" napisz: „Zaczynamy maile od imienia klienta, nie używamy słowa «zapraszamy», kończymy pytaniem otwartym."\n\n**Daty i wersje** — na początku pliku dodaj `Aktualizacja: 2026-04`. Za pół roku docenisz."}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"markdown","content":"## Scena 4 — Pliki .md jako baza wiedzy dla agentów\n\nZarówno **Claude**, jak i **Gemini** możesz wyposażyć w pliki `.md` jako stały kontekst:\n\n**W Claude Projects** — wgrywasz pliki `.md` do projektu. Każda rozmowa w tym projekcie automatycznie dostaje te pliki jako kontekst. Agent „wie" wszystko co w nich zapisałeś, bez wklejania za każdym razem.\n\n**W n8n i Flowise** — masz węzeł „Document Loader", który ładuje plik `.md` z dysku lub GitHuba. Agent przy każdym uruchomieniu odczytuje aktualną wersję — wystarczy zaktualizować plik, żeby zmienić zachowanie agenta.\n\n**W Gemini (przez Google Drive)** — wgrywasz `.md` na Drive, podajesz link do NotebookLM lub używasz w Gemini Advanced.\n\nKluczowa zaleta: **jeden plik, może służyć dla wielu agentów**."}]'),
(v_lesson_id, 'technical', 7, '[{"kind":"code","language":"text","label":"Scena 5 — Proponowany system folderów","code":"/wiedza\n  /firma\n    misja.md\n    ton_komunikacji.md\n  /produkty\n    oferta.md\n    faq.md\n  /klienci\n    klient_A.md\n    klient_B.md\n  /agenci\n    agent_supportu.md\n    agent_contentu.md"}]'),
(v_lesson_id, 'technical', 8, '[{"kind":"tip","title":"Podsumowanie","desc":"Co zapamiętać:\n- Pliki `.md` to najprostszy i najbardziej przenośny format wiedzy dla AI\n- Dobra struktura = `#` nagłówki + krótkie, konkretne sekcje tematyczne\n- Claude Projects, n8n, Flowise i Gemini — wszystkie potrafią ładować `.md` jako kontekst\n- Jeden dobrze napisany plik wiedzy zastępuje dziesiątki powtarzających się promptów"}]');

-- Lesson 2: Systemy agentowe bez kodu
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_nocode, 'Systemy agentowe bez kodu', 2, '12 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Zrozumiesz, czym są systemy wieloagentowe, jak zaprojektować sieć agentów, którzy ze sobą współpracują — i dlaczego to potężniejsze niż jeden, nawet bardzo mądry model."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Jeden agent vs. armia agentów\n\nWyobraź sobie, że chcesz zorganizować konferencję. Możesz zatrudnić jedną osobę, która napisze zaproszenia, zarezerwuje salę, zamówi catering, ogarnie livestream i odpowie na 300 e-maili. Skończy po 3 tygodniach. Albo padnie.\n\nAlternatywa: zatrudniasz koordynatora i kilku specjalistów. Każdy robi swoje, koordynator spina całość. Konferencja gotowa w 3 dni.\n\n**Systemy agentowe działają dokładnie tak samo.** Zamiast jednego modelu AI, który robi wszystko — tworzysz sieć wyspecjalizowanych agentów, z których każdy dostaje jedno zadanie i dowozi."}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"markdown","content":"## Scena 2 — Jak wygląda sieć agentów?\n\nTypowa sieć ma trzy rodzaje ról:\n\n**Orchestrator (dyrygent)** — przyjmuje zadanie od użytkownika, dzieli je na podzadania i przypisuje do właściwych agentów. Sam nie wykonuje pracy — zarządza.\n\n**Workers (wykonawcy)** — wyspecjalizowani agenci. Jeden pisze posty, drugi szuka danych w internecie, trzeci generuje raporty, czwarty wysyła maile.\n\n**Memory / Tools (zasoby)** — bazy wiedzy, arkusze Google, webhooki, API. Agenci sięgają po nie w razie potrzeby.\n\n> Przykład przepływu: Użytkownik → Orchestrator → „Znajdź mi 10 trendów w AI" → Agent Researcher → Agent Writer → Agent Publisher"}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"markdown","content":"## Scena 3 — Narzędzia No-Code do budowania sieci agentów\n\nNie musisz pisać ani linijki kodu, żeby zbudować taki system:\n\n**n8n** — świetny do orkiestracji przepływów z wieloma krokami. Możesz budować sieć agentów łącząc węzły AI Agent → narzędzia → kolejny węzeł.\n\n**Make (dawne Integromat)** — podobny do n8n, jeszcze bardziej przyjazny wizualnie. Dobry do prostszych sieci.\n\n**Flowise** — open-source, stworzony specjalnie do budowania sieci agentów i chatbotów. Masz gotowe bloki: Agent, Tool, Memory, Chain. Przeciągasz, łączysz, odpalasz.\n\n**Relevance AI** — bardziej zaawansowany, komercyjny. Pozwala tworzyć całe „zespoły" agentów z rolami, uprawnieniami i pamięcią współdzieloną.\n\nZasada: jeśli coś możesz narysować na kartce jako schemat blokowy → możesz zbudować w jednym z tych narzędzi."}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"markdown","content":"## Scena 4 — Pułapki, czyli gdzie No-Code boli\n\n**Pętla nieskończona** — agent A wysyła zadanie do agenta B, który odsyła je z powrotem do A. Zawsze definiuj warunek stopu.\n\n**Zbyt długi kontekst** — jeśli agenci wysyłają sobie pełne transkrypcje zamiast podsumowań, model szybko zapomina początek rozmowy. Niech każdy agent przekazuje dalej tylko to, co niezbędne.\n\n**Brak logowania** — gdy coś idzie nie tak, trudno znaleźć winowajcę. Włącz logi w n8n/Flowise od pierwszego dnia.\n\n**Zbyt dużo agentów** — nie musisz budować NASA. Zacznij od 2–3 agentów, skaluj gdy masz problem, który tego wymaga."}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"markdown","content":"## Scena 5 — Twój pierwszy system: Research Bot w 30 minut\n\nBudujemy najprostszy użyteczny system: **bot, który codziennie rano szuka nowych wpisów na temat który cię interesuje i wysyła ci podsumowanie mailem.**\n\nPotrzebujesz w Flowise lub n8n:\n\n1. **Agent Researcher** — narzędzie: web search (Tavily lub SerpAPI), prompt: „Znajdź 5 najnowszych artykułów o [temat] z ostatnich 24h"\n2. **Agent Summarizer** — przyjmuje wyniki od Researchera, pisze 3-zdaniowe podsumowanie każdego artykułu\n3. **Węzeł Send Email** — wysyła gotowy raport na twój adres\n\nCały przepływ: wyzwalacz czasowy (codziennie o 7:00) → Researcher → Summarizer → Email. Gotowe."}]'),
(v_lesson_id, 'technical', 7, '[{"kind":"tip","title":"Podsumowanie","desc":"Co zapamiętać:\n- System agentowy = podział pracy między wyspecjalizowanych \"pracowników AI\"\n- Orchestrator deleguje, Workers wykonują, Tools i Memory to ich zasoby\n- Flowise i n8n to najprostsze narzędzia no-code do zbudowania takiej sieci\n- Zacznij mały: 2–3 agenci rozwiązują 80% problemów"}]');

-- Lesson 3: AI w Social Media i Content Automation
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_nocode, 'AI w Social Media i Content Automation', 3, '10 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Po tej lekcji będziesz wiedzieć, jak zamienić jeden pomysł na gotowy post, grafikę i odpowiedź do klienta — zanim zdążysz wypić kawę."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Fabryka contentu: jeden pomysł, sto formatów\n\nWpadasz na pomysł wpisu: *„3 błędy przy onboardingu pracowników."* Dawniej pisałeś post, wymyślałeś grafikę, tłumaczyłeś to samo na angielski i modliłeś się, żeby algorytm to zauważył.\n\nDziś? Wpisujesz temat do modelu AI, a on produkuje:\n- wersję na LinkedIn (długa, merytoryczna),\n- wersję na X (zwięzła, z hakiem),\n- skrypt do TikToka (mówiony, z punktami),\n- propozycję grafiki do Canvy.\n\nKluczem jest dobry prompt startowy z kontekstem: *kim jesteś, do kogo piszesz, jaki styl.* Stwórz go raz, używaj zawsze — to Twój „tone of voice template"."}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"markdown","content":"## Scena 2 — Google Labs: Stitch, Whisk i Pomelli\n\nGoogle cicho wypuściło kilka narzędzi, które robią furorę wśród designerów i marketerów.\n\n**Whisk** — wrzucasz zdjęcie produktu lub bohatera, opisujesz styl (np. *„japoński plakat lat 80"*), a Whisk generuje spójne grafiki. Idealne do budowania wizualnej tożsamości serii postów.\n\n**Stitch** — łączy elementy wizualne z różnych źródeł w jeden obraz. Chcesz swojego avatara na tle Manhattanu w stylu retro? Stitch to ogarnie.\n\n**Pomelli** — asystent do edycji zdjęć głosem i tekstem. Mówisz *„usuń tło, dodaj gradient fioletowy, powiększ logo"* — i masz gotową grafikę bez Photoshopa.\n\nPraktyka: zaplanuj serię 4 postów na LinkedIn. Użyj Whisku do wygenerowania spójnych ilustracji — ta sama paleta kolorów, ten sam nastrój."}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"markdown","content":"## Scena 3 — Automatyczna dystrybucja: n8n + API platform\n\nNapisanie postu to 20% roboty. Dystrybucja to pozostałe 80% — i tu AI + automatyzacja robi największą różnicę.\n\nSchemat przepływu:\n1. **Wejście:** Wpisujesz temat/briefing do formularza (Google Form lub Notion)\n2. **Generowanie:** n8n woła Claude lub Gemini, który produkuje wersje na różne platformy\n3. **Grafika:** Canva API lub Whisk generuje obrazek\n4. **Publikacja:** n8n wysyła post na LinkedIn, tweetuje przez X API, zapisuje TikTok skrypt do pliku\n5. **Raport:** Dostajesz Slack/email z podsumowaniem co poszło i kiedy\n\nRaz ustawiony workflow publikuje za Ciebie — Ty tylko zatwierdzasz treść."}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"markdown","content":"## Scena 4 — Customer Support Bot: Twój pracownik 24/7\n\nKlasyczny scenariusz: klient pisze do Ciebie w niedzielę wieczór z pytaniem o cennik. Ty śpisz. Klient odpływa do konkurencji.\n\nRozwiązanie: prosty bot oparty na Claude lub Gemini z bazą wiedzy (FAQ, cennik, polityka zwrotów w pliku .md lub Notion).\n\n**No-Code stack:**\n- **Zapier lub n8n** — odbiera wiadomość z maila, Messengera lub czatu na stronie\n- **Claude API** — przetwarza pytanie z kontekstem z Twojej bazy wiedzy\n- **Odpowiedź** wraca automatycznie do klienta w ciągu sekund\n\nWażne: bot nie musi wiedzieć wszystkiego. Wystarczy że zna 80% typowych pytań i wie, kiedy powiedzieć „zaraz odpisze Ci człowiek." To jest feature, nie bug."}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"tip","title":"Podsumowanie","desc":"Social media to nie tylko pisanie — to system. AI pomaga Ci zbudować ten system raz i działać szybciej niż konkurencja, która nadal siedzi i wymyśla treści od zera.\n\nStwórz swój Content Pipeline v1.0: tone of voice template → wersje postów → grafika z Whisku → przepływ n8n."}]');

-- Lesson 4: Twój osobisty analityk danych (AI Data Agent)
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_nocode, 'Twój osobisty analityk danych (AI Data Agent)', 4, '12 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Po tej lekcji będziesz umiał zamienić zwykły arkusz kalkulacyjny w maszynę analityczną. Żadnych formuł. Żadnego bólu głowy. Tylko ty, AI i dane, które w końcu zaczną coś mówić."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Problem, który wszyscy znają\n\nMasz plik Excela z 800 wierszami danych sprzedażowych. Twój szef pyta: *„No i co z tego wynika?"*\n\nTy otwierasz arkusz. Patrzysz. Arkusz patrzy na ciebie. Nikt nic nie mówi.\n\nKiedyś żeby „wyciągnąć wnioski" z danych musiałeś znać formuły (`SUMIF`, `VLOOKUP`, `INDEX/MATCH` i inne czary-mary), albo zatrudnić kogoś kto je zna.\n\nDziś masz coś lepszego: AI, który **czyta twoje dane i tłumaczy je na ludzki język**."}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"markdown","content":"## Scena 2 — Oficjalne integracje: Claude w Excelu, Gemini w Google Sheets\n\n**Microsoft Excel + Claude / Copilot**\nOtwierasz panel boczny Clauda bezpośrednio w Excelu i rozmawiasz o swoich danych jak z analitykiem siedzącym obok. Możesz zapytać o trendy, poprosić o automatyczne wykresy, podzielić dane na segmenty.\n\n**Google Sheets + Gemini**\nGemini siedzi w bocznym panelu Sheets i reaguje na twoje pytania kontekstowo — wie, jakie dane masz w arkuszu, i operuje bezpośrednio na nich.\n\nTo jest kluczowa zmiana: **AI wchodzi do twojego środowiska pracy, a nie ty wychodzisz do AI**."}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"markdown","content":"## Scena 3 — Podłącz własne AI do arkusza (bez kodu)\n\n**Opcja A: Eksport do CSV + Claude.ai**\n\nWiedz o jednej ważnej rzeczy: AI znacznie lepiej radzi sobie z plikiem CSV niż z treścią wklejoną wprost z arkusza. Skopiowane komórki często tracą strukturę. CSV jest czysty i AI doskonale go rozumie.\n\nPlik → Pobierz → CSV → wrzuć do Claude jako załącznik z pytaniem: *„Przeanalizuj te dane i powiedz mi, co jest niepokojące"*. Działa zaskakująco dobrze nawet dla kilkuset wierszy.\n\n**Opcja B: n8n + AI + Google Sheets (automatyczne)**\n\nZbuilduj workflow, który co poniedziałek pobiera dane z Google Sheets, wysyła je do Claude API, Claude je analizuje i pisze podsumowanie, a podsumowanie ląduje w emailu do szefa. Zero ręcznej pracy."}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"markdown","content":"## Scena 4 — Co możesz poprosić AI żeby zrobił z danymi\n\n**Analiza trendów** — *„Czy sprzedaż rośnie czy spada? Pokaż mi, w którym tygodniu był szczyt"*\n\n**Wykrywanie anomalii** — *„Czy są jakieś wartości, które wyglądają podejrzanie? Coś, co bardzo odstaje od reszty?"*\n\n**Segmentacja** — *„Podziel klientów na grupy według ich zachowania zakupowego"*\n\n**Prognozy** — *„Na podstawie danych z ostatnich 6 miesięcy — jak może wyglądać następny kwartał?"*\n\n**Automatyczne podsumowania** — *„Napisz mi raport wykonawczy z tych danych. Maksymalnie 5 zdań, dla osoby, która nie lubi liczb"*\n\nKluczowa zasada: **pytaj konkretnie**. Im bardziej konkretne pytanie, tym bardziej użyteczna odpowiedź."}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"markdown","content":"## Scena 5 — Kiedy arkusz to za mało: AI Data Agent\n\nCo jeśli chcesz, żeby AI **sam monitorował twoje dane i alarmował, gdy coś się dzieje?**\n\nJak zbudować bez kodu:\n- **Google Sheets** jako źródło danych (aktualizowane ręcznie lub przez Zapier/Make)\n- **n8n** jako silnik automatyzacji (harmonogram: co dzień / co tydzień)\n- **Claude API** jako mózg analityczny\n- **Email lub Slack** jako kanał powiadomień\n\nCały przepływ: dane → AI → wnioski → ty. A ty zajmujesz się rzeczami ważniejszymi niż przeglądanie tabelek."}]'),
(v_lesson_id, 'technical', 7, '[{"kind":"tip","title":"Podsumowanie","desc":"Dane bez analizy to tylko liczby. Analiza bez działania to tylko ciekawostka. Ale dane + AI + automatyzacja = system, który pracuje dla ciebie 24/7.\n\nNauczyłeś się: korzystać z wbudowanych AI w Excelu i Google Sheets, eksportować do CSV, budować automatyczny raport z n8n + AI, i czym jest AI Data Agent."}]');

-- ============================================================
-- ŚCIEŻKA KOD (mode=''technical'')
-- ============================================================

-- Lesson 1: Claude Code IDE w praktyce
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_kod, 'Claude Code IDE w praktyce', 1, '15 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Dowiesz się czym jest Claude Code, jak go uruchomić i jak wpiąć go w swój codzienny workflow programisty — tak żeby nie był kolejną zakładką w przeglądarce, tylko prawdziwym partnerem przy kodzie."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Czym właściwie jest Claude Code?\n\nWyobraź sobie, że zatrudniasz seniora do pracy przy Twoim projekcie. Ale zamiast siedzieć obok Ciebie, on *żyje w terminalu*. Widzi całe repozytorium, rozumie kontekst, pisze kod, uruchamia testy, poprawia błędy — i robi to wszystko w pętli, bez przerwy, aż problem zniknie.\n\nTo właśnie Claude Code. Nie jest to plugin do IDE z podpowiedziami. To **agent działający w wierszu poleceń**, który widzi Twoje pliki i może na nich działać.\n\nTechnicznie: Claude Code to CLI (Command Line Interface) od Anthropic. Instalujesz go raz, uruchamiasz w folderze projektu, i rozmawiasz z nim jak z człowiekiem."}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"code","language":"bash","label":"Scena 2 — Instalacja w 3 minuty (wymaga Node.js 18+)","code":"# Sprawdź wersję Node.js\nnode -v\n\n# Zainstaluj Claude Code\nnpm install -g @anthropic-ai/claude-code\n\n# Wejdź do projektu i uruchom\ncd moj-projekt\nclaude"}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"tip","title":"💡 Wskazówka dotycząca autoryzacji","desc":"Nie potrzebujesz klucza API jeśli masz subskrypcję Claude Pro lub Max. Jeśli korzystasz z API — ustawiasz zmienną środowiskową ANTHROPIC_API_KEY.\n\nPrzy pierwszym uruchomieniu zaloguje Cię przez przeglądarkę (konto Anthropic). Po autoryzacji — gotowe."}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"code","language":"text","label":"Scena 3 — Przykłady komend, które naprawdę działają","code":"> Dodaj obsługę błędów do funkcji fetchUser w pliku api/users.ts\n> Napisz testy jednostkowe do tego modułu\n> Dlaczego ten kod zwraca undefined? Przejrzyj plik i powiedz mi co jest nie tak\n> Zrefaktoruj ten komponent — jest zbyt duży, podziel go na mniejsze\n> Skonfiguruj ESLint z regułami dla projektu Next.js"}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"markdown","content":"## Scena 4 — Integracja z VS Code i JetBrains\n\nNie musisz rezygnować ze swojego ulubionego edytora. Claude Code działa świetnie jako osobne okno terminala obok IDE.\n\nAle jest też coś lepszego: **rozszerzenia**.\n\n- **VS Code:** Zainstaluj rozszerzenie *Claude Code for VS Code* ze sklepu. Otrzymujesz panel boczny z chatem bezpośrednio w edytorze — możesz zaznaczyć fragment kodu i zapytać o niego bez przełączania kontekstu.\n- **JetBrains (IntelliJ, WebStorm, PyCharm):** Analogiczne rozszerzenie w JetBrains Marketplace.\n\n**Złota zasada:** terminal = do dużych zadań (refaktoryzacja modułu, pisanie testów). Panel w IDE = do małych pytań (co robi ta funkcja, jak poprawić ten błąd)."}]'),
(v_lesson_id, 'technical', 7, '[{"kind":"code","language":"bash","label":"Scena 5 — Tryb YOLO (dla odważnych)","code":"# Domyślnie Claude Code pyta przed każdą zmianą.\n# Tryb bez potwierdzeń:\nclaude --dangerously-skip-permissions\n\n# Używaj TYLKO na projektach gdzie masz git i regularne commity.\n# W najgorszym razie: git checkout i jesteś w domu."}]'),
(v_lesson_id, 'technical', 8, '[{"kind":"code","language":"markdown","label":"Scena 6 — Plik CLAUDE.md — pamięć projektu","code":"# CLAUDE.md\n\n## Stack\nNext.js 15, TypeScript, Tailwind, Prisma\n\n## Uruchomienie\nnpm run dev (port 3000)\n\n## Konwencje\n- Komponenty w PascalCase\n- Zawsze TypeScript, nigdy any\n- Testy: Vitest + Testing Library\n\n## Czego nie ruszać\n- /lib/legacy — stary kod, nie dotykamy"}]'),
(v_lesson_id, 'technical', 9, '[{"kind":"table","headers":["Plan","Koszt","Kiedy warto"],"rows":[["Claude Pro","$20/mc","Dostęp do Claude Code bez klucza API. Dla większości deweloperów to wystarczy."],["Claude Max","$100/mc","5x więcej tokenów, priorytet w kolejce. Jeśli Claude Code to Twoje główne narzędzie."],["API (pay-per-use)","~$3/M tokenów wejściowych","Dla firm i power userów. Refaktoryzacja 2000 linii = $0.15–3."]]}]'),
(v_lesson_id, 'technical', 10, '[{"kind":"tip","title":"Podsumowanie","desc":"Claude Code to:\n- Agent CLI działający bezpośrednio na Twoim projekcie\n- Integruje się z VS Code i JetBrains\n- Rozumie kontekst całego repo\n- Można go nauczyć projektu przez plik CLAUDE.md\n\nUżywaj --verbose żeby widzieć zużycie tokenów w czasie rzeczywistym."}]');

-- Lesson 2: Inżynieria systemów AI
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_kod, 'Inżynieria systemów AI', 2, '15 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Nauczysz się jak podejść do budowania aplikacji z AI tak, żeby po 2 tygodniach nie siedzieć z 800-liniowym plikiem, który jakoś działa, ale nie wiadomo jak."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Dlaczego spaghetti powstaje tak szybko?\n\nKlasyczny scenariusz:\n\n> „Hej Claude, napisz mi aplikację do zarządzania zadaniami."\n> *Claude pisze 300 linii w jednym pliku.*\n> „Teraz dodaj logowanie."\n> *Dorzuca kolejne 100 linii do tego samego pliku.*\n> „Teraz dodaj powiadomienia email."\n> *Plik ma 600 linii i nikt już nie wie co jest gdzie.*\n\nProblem nie jest w Claude. Problem jest w tym, że **zacząłeś od kodu, nie od architektury**.\n\nAI jest świetne w generowaniu kodu. Ale generuje to, o co go prosisz — jeśli nie dasz mu struktury, sam sobie ją wymyśli. I nie będzie to ta sama struktura co w kolejnym prompcie.\n\n**Rozwiązanie: najpierw architektura, potem kod.**"}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"markdown","content":"## Scena 2 — Krok 1: Zanim napiszesz linię kodu, zaprojektuj z AI\n\nZanim powiesz „napisz mi aplikację X", powiedz najpierw:\n\n> *„Chcę zbudować aplikację do [opis]. Pomóż mi zaprojektować architekturę — jakie moduły/komponenty będą potrzebne, jak będą ze sobą rozmawiać i jaka struktura folderów będzie sensowna dla tego projektu."*\n\nClaude wróci z propozycją struktury. **Zaakceptuj lub skoryguj tę strukturę.** To jest Twój kontrakt z AI na resztę projektu.\n\n**Złota zasada:** architektura ustalona raz, na początku = AI zawsze wie gdzie co wrzucać."}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"code","language":"text","label":"Przykład struktury projektu wygenerowanej przez Claude","code":"src/\n  auth/          ← logowanie, sesje\n  tasks/         ← logika zadań\n  notifications/ ← email, push\n  db/            ← modele i migracje\n  api/           ← endpointy\n  ui/            ← komponenty"}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"code","language":"markdown","label":"Scena 3 — Plik PROJECT.md jako pamięć projektu","code":"# PROJECT.md\n\n## Co to jest\nAplikacja do zarządzania zadaniami dla małych zespołów.\n\n## Stack\nNext.js 15, TypeScript, Prisma, PostgreSQL\n\n## Architektura\nsrc/auth/ — logowanie\nsrc/tasks/ — logika zadań\n...\n\n## Zasady\n- Komponenty tylko funkcyjne\n- Każdy moduł ma własne testy\n- API w REST, nie GraphQL"}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"markdown","content":"## Scena 3 — Krok 2: Buduj moduł po module\n\nMasz architekturę. Teraz budujesz po jednym kawałku, z pełnym kontekstem:\n\n> *„Pracujemy nad projektem [nazwa]. Struktura jest taka: [wklej strukturę]. Teraz zbuduj moduł `auth/` — rejestracja i logowanie przez email. Użyj [stack]. Trzymaj się tej struktury folderów."*\n\nKlucz: **zawsze podawaj kontekst projektu na początku rozmowy**. Claude nie pamięta poprzednich sesji — bez tego zacznie od zera i zepsuje strukturę.\n\nPrzydatny trick: trzymaj w projekcie plik `PROJECT.md` z opisem architektury. Wklejaj jego zawartość na początku każdej sesji z AI."}]'),
(v_lesson_id, 'technical', 7, '[{"kind":"markdown","content":"## Scena 4 — Code Review z AI zanim commit\n\nNapisałeś nowy moduł z pomocą AI. Zanim wrzucisz go do repozytorium, zrób jedno dodatkowe pytanie:\n\n> *„Przejrzyj ten kod pod kątem: czy pasuje do reszty architektury? Czy nie łamie żadnej zasady z PROJECT.md? Czy jest coś co za miesiąc będzie problemem?"*\n\nAI wcieli się w rolę seniora robiącego review. Przykładowe odpowiedzi:\n- *„Ten komponent robi za dużo — logika biznesowa miesza się z UI"*\n- *„Importujesz bezpośrednio z modułu auth w module tasks — to tworzy zależność w złą stronę"*\n- *„Brakuje obsługi błędów w 3 miejscach"*"}]'),
(v_lesson_id, 'technical', 8, '[{"kind":"markdown","content":"## Scena 5 — Debug z kontekstem\n\nApka nie działa. Zamiast:\n❌ *„Dlaczego ten kod nie działa?"* + wklejenie 100 linii\n\nZrób:\n✅ *„Mam błąd [treść błędu]. Kontekst: używamy [stack], plik to [ścieżka], ten kod odpowiada za [co robi]. Oto kod: [fragment]. Co jest nie tak i jak to naprawić nie psując reszty architektury?"*\n\nRóżnica jest ogromna. W pierwszym przypadku Claude zgaduje. W drugim — rozwiązuje Twój konkretny problem w Twoim konkretnym kontekście."}]'),
(v_lesson_id, 'technical', 9, '[{"kind":"tip","title":"Podsumowanie — Proces bez spaghetti","desc":"1. Architektura najpierw — poproś AI o projekt struktury zanim zaczniesz kodować\n2. Plik PROJECT.md — jeden plik z kontekstem projektu, który wklejasz na start każdej sesji\n3. Moduł po module — buduj małymi kawałkami z pełnym kontekstem\n4. Code review przed commitem — AI jako senior reviewer\n5. Debug z kontekstem — zawsze podaj stack, ścieżkę, cel i błąd"}]');

-- Lesson 3: Najlepsze TechStacki w praktyce
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_kod, 'Najlepsze TechStacki w praktyce', 3, '12 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Zrozumiesz, czym jest tech stack, jakie kombinacje narzędzi sprawdzają się najlepiej przy budowaniu projektów z AI — i jak nie utknąć w nieskończonej pętli wyboru technologii."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Czym jest tech stack?\n\nTech stack to zestaw technologii, których używasz do zbudowania aplikacji. Trochę jak przepis kulinarny — masz składniki (narzędzia), metodę (architekturę) i finalny efekt (działający produkt).\n\nZły wybór tech stacku to jak próba zrobienia sushi w blenderze. Technicznie możliwe. Praktycznie — niekoniecznie mądre.\n\nDobry tech stack w 2026 spełnia trzy warunki:\n- **Szybkość startu** — możesz mieć działający prototyp w weekend\n- **Skalowalność** — gdy projekt rośnie, narzędzia nie blokują\n- **Integracja z AI** — łatwo podpinasz modele, agenty, bazy wektorowe"}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"markdown","content":"## Scena 2 — Frontend: React i jego przyjaciele\n\n**React** to wciąż król frontendów. Większość narzędzi AI, dashboardów i paneli administracyjnych jest w nim zbudowana — co oznacza mnóstwo gotowych komponentów, tutoriali i wsparcia od modeli AI.\n\n**Next.js** — framework nadbudowany nad Reactem. Daje routing, server-side rendering i API routes w jednym. Możesz zbudować pełną aplikację bez osobnego backendu.\n\n**Tailwind CSS** — style przez klasy w HTML. Zamiast pisać CSS, dodajesz klasy: `flex`, `gap-4`, `text-xl`. Brzmi dziwnie, działa świetnie, AI generuje to doskonale.\n\n**Vercel** — hosting dla Next.js projektów. Deploy przez `git push`. Dosłownie tyle.\n\nGotowy stack frontendowy: **Next.js + Tailwind + Vercel** = od zera do działającej strony w kilka godzin."}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"markdown","content":"## Scena 3 — Backend: Supabase jako baza wszystkiego\n\n**Supabase** to open-source alternatywa dla Firebase — prawdopodobnie najlepszy wybór dla osób, które nie chcą zarządzać własnym serwerem, ale potrzebują prawdziwej bazy danych.\n\nDostajesz w jednym pakiecie:\n- **PostgreSQL** — pełnoprawna baza relacyjna\n- **Auth** — logowanie przez e-mail, Google, GitHub bez kodowania\n- **Storage** — przechowywanie plików (obrazy, PDFy, nagrania)\n- **Edge Functions** — serverless kod po stronie serwera\n- **Realtime** — synchronizacja danych w czasie rzeczywistym\n\nDla projektów AI szczególnie ważna jest obsługa **pgvector** — możesz zbudować własny RAG bezpośrednio w Supabase, bez osobnej bazy wektorowej.\n\nStack backendowy: **Supabase + Edge Functions** = backend bez utrzymywania serwera."}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"markdown","content":"## Scena 4 — Docker, czyli \"u mnie działa\" przestaje być wymówką\n\n**Docker** pakuje aplikację razem ze wszystkimi jej zależnościami w kontener — przenośne środowisko, które działa tak samo wszędzie.\n\nKiedy Docker jest potrzebny:\n- Lokalnie uruchamiasz modele AI (np. przez LM Studio lub Ollama)\n- Budujesz Flowise, n8n lub inne narzędzia self-hosted\n- Chcesz, żeby twój projekt dało się wdrożyć na dowolnym serwerze\n\nPodstawowy przepływ:\n1. Piszesz `Dockerfile` — opis środowiska aplikacji\n2. Budujesz obraz: `docker build`\n3. Uruchamiasz: `docker run`\n4. Na serwerze: to samo, jeden do jednego\n\nDocker Compose pozwala uruchamiać kilka serwisów jednocześnie (np. n8n + baza danych) jedną komendą."}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"markdown","content":"## Scena 5 — Serwer Linux + GitHub: fundament poważnych projektów\n\nJeśli chcesz wyjść poza bezpłatne poziomy Vercela i Supabase — potrzebujesz **własnego serwera VPS**.\n\nNajpopularniejszy wybór: **Ubuntu na Hetzner, DigitalOcean lub Contabo**. Płacisz kilka–kilkanaście euro miesięcznie, dostajesz pełną kontrolę.\n\nDla startu z małym budżetem: **mikr.us** — polska usługa VPS (~130 zł/rok). Idealna do prywatnych projektów i zabawy z AI.\n\n**GitHub** spina całość jako centrum kodu i CI/CD:\n- Kod trzymasz w repozytorium\n- GitHub Actions automatycznie testuje i wdraża przy każdym pushu\n- Agenty AI (jak Jules) pracują na tym samym kodzie\n\nTypowy przepływ: `git push` → GitHub Actions → automatyczny deploy na serwer → aplikacja zaktualizowana."}]'),
(v_lesson_id, 'technical', 7, '[{"kind":"tip","title":"Złoty stack 2026 dla projektów AI","desc":"Frontend: Next.js + Tailwind + Vercel\nBackend/Baza: Supabase (PostgreSQL + Auth + pgvector)\nKonteneryzacja: Docker + Docker Compose\nInfrastruktura: Serwer Linux (Ubuntu) + GitHub + Actions\n\nNie musisz używać wszystkiego od razu. Zacznij od Next.js + Supabase. Dodaj Docker gdy zaczniesz self-hostować narzędzia. Własny serwer — gdy projekt tego wymaga."}]');

-- Lesson 4: Zaawansowani agenci (Multi-Agent Networks)
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_kod, 'Zaawansowani agenci (Multi-Agent Networks)', 4, '18 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Nauczysz się jak budować systemy złożone z kilku wyspecjalizowanych agentów AI, które współpracują ze sobą — zamiast jednego wszechwiedzącego agenta który robi wszystko i wszystko myli."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Jeden agent vs. sieć agentów\n\nWyobraź sobie firmę obsługi klienta. Możesz zatrudnić jedną osobę, która odbiera telefon, sprawdza zamówienia, pisze odpowiedzi, eskaluje problemy i wystawia faktury. Albo możesz mieć zespół specjalistów.\n\n**Jeden „super-agent" który robi wszystko:**\n- Szybko traci kontekst przy złożonych zadaniach\n- System promptu rośnie do niebotycznych rozmiarów\n- Jeden błąd psuje całe zadanie\n\n**Sieć wyspecjalizowanych agentów:**\n- Każdy agent ma jedno zadanie i robi je świetnie\n- Agenci przekazują sobie wyniki jak w taśmie produkcyjnej\n- Łatwo podmienić/ulepszyć pojedynczy element"}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"markdown","content":"## Scena 2 — Anatomia sieci agentów\n\n**Orchestrator** — szef projektu. Dostaje zadanie od użytkownika, dzieli je na podzadania i deleguje do agentów. Sam nie wykonuje pracy — koordynuje.\n\n**Agenci specjalistyczni** — każdy ma swoją rolę:\n- Agent badawczy — szuka informacji\n- Agent piszący — generuje treść\n- Agent weryfikujący — sprawdza jakość\n- Agent wykonawczy — wywołuje API, pisze pliki, wysyła maile\n\n**Narzędzia (Tools)** — to co agenci mogą robić: szukać w Google, czytać pliki, uruchamiać kod, wysyłać requesty HTTP."}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"code","language":"python","label":"Przykład orchestratora w Pythonie","code":"async def orchestrate(task: str):\n    # 1. Podziel zadanie\n    subtasks = await planner_agent.plan(task)\n\n    # 2. Deleguj do specjalistów\n    research = await research_agent.run(subtasks.research)\n    draft = await writer_agent.run(subtasks.write, context=research)\n    final = await reviewer_agent.run(draft)\n\n    return final"}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"markdown","content":"## Scena 3 — Pliki .md jako „mózg" agenta\n\nKażdy agent potrzebuje dwóch rzeczy: **instrukcji** (jak ma działać) i **kontekstu** (co wie o projekcie/firmie/zadaniu).\n\nZamiast trzymać to w bazie danych lub hardkodować w kodzie — użyj plików `.md`. Podejście banalnie proste i zaskakująco potężne.\n\nZaleta: możesz edytować zachowanie agenta bez dotykania kodu. Wystarczy zmienić plik `.md`."}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"code","language":"text","label":"Przykładowa struktura plików agentów","code":"agents/\n  orchestrator/\n    SYSTEM.md      ← rola i zasady orchestratora\n    CONTEXT.md     ← co wie o projekcie\n  researcher/\n    SYSTEM.md      ← jak szukać, z jakich źródeł\n    MEMORY.md      ← co już zbadał (aktualizowany po każdym runie)\n  writer/\n    SYSTEM.md      ← styl pisania, ton, format\n    EXAMPLES.md    ← przykłady dobrej i złej odpowiedzi"}]'),
(v_lesson_id, 'technical', 7, '[{"kind":"code","language":"python","label":"Ładowanie agenta z pliku .md","code":"def load_agent(agent_name: str) -> str:\n    system = Path(f\"agents/{agent_name}/SYSTEM.md\").read_text()\n    context = Path(f\"agents/{agent_name}/CONTEXT.md\").read_text()\n    return f\"{system}\\n\\n---\\n\\n{context}\"\n\nresearcher = ClaudeAgent(\n    system_prompt=load_agent(\"researcher\"),\n    tools=[web_search, read_file]\n)"}]'),
(v_lesson_id, 'technical', 8, '[{"kind":"markdown","content":"## Scena 4 — Jak agenci przekazują sobie wyniki?\n\n**1. Pipeline (taśma)** — wynik jednego agenta to wejście kolejnego:\n```\nUżytkownik → Orchestrator → Researcher → Writer → Reviewer → Użytkownik\n```\nProsty, przewidywalny, łatwy do debugowania. Dobry dla zadań liniowych.\n\n**2. Blackboard (tablica)** — wszyscy agenci piszą i czytają ze wspólnego pliku. Każdy agent dopisuje swoje wyniki do tablicy i może czytać co zrobili poprzednicy. Dobry dla zadań równoległych lub gdy agenci muszą reagować na siebie nawzajem."}]'),
(v_lesson_id, 'technical', 9, '[{"kind":"markdown","content":"## Scena 5 — Pułapki multi-agent i jak ich unikać\n\n**Pułapka 1: Agent loop** — agent A pyta agenta B, który pyta agenta A. Rozwiązanie: zawsze definiuj MAX_ITERATIONS.\n\n**Pułapka 2: Rosnący kontekst** — po 20 krokach agent ma 50k tokenów historii. Rozwiązanie: co N kroków uruchom „summarizer agent" który ściska historię do 1 paragrafu.\n\n**Pułapka 3: Brak logowania** — coś poszło nie tak, ale nie wiadomo gdzie. Rozwiązanie: każdy krok każdego agenta zapisuj do pliku z timestampem."}]'),
(v_lesson_id, 'technical', 10, '[{"kind":"code","language":"python","label":"Zabezpieczenia: limit iteracji i logowanie","code":"MAX_ITERATIONS = 10\nfor i in range(MAX_ITERATIONS):\n    result = agent.step()\n    if result.is_final:\n        break\n\ndef log_step(agent: str, input: str, output: str):\n    with open(\"agent_log.md\", \"a\") as f:\n        f.write(f\"\\n## {datetime.now()} | {agent}\\n\")\n        f.write(f\"**Input:** {input[:200]}\\n\")\n        f.write(f\"**Output:** {output[:200]}\\n\")"}]'),
(v_lesson_id, 'technical', 11, '[{"kind":"markdown","content":"## Scena 6 — Koszt sieci agentów\n\nSieć agentów to mnożnik kosztów. Każdy agent wywołuje model — jeśli masz 4 agentów i każdy przetwarza 5000 tokenów, jedno zadanie = 20 000 tokenów.\n\n**Optymalizacja kosztów:**\n\n1. **Hierarchia modeli:** Orchestrator i reviewer = Claude Sonnet (droższy, mądrzejszy). Agenty wykonawcze = Claude Haiku (tańszy). Oszczędność: 60–80%.\n\n2. **Cache prompt:** Jeśli system prompt agenta jest długi i stały — użyj prompt caching API. Cached tokeny są ~10× tańsze.\n\n3. **Limit iteracji:** Bez limitu agent może kręcić się w pętli. `MAX_ITERATIONS = 10` to zabezpieczenie logiczne i budżetowe.\n\n> ⚠️ Przed odpaleniem agenta w pętli — przetestuj na 1 zadaniu i sprawdź zużycie tokenów przez logi."}]'),
(v_lesson_id, 'technical', 12, '[{"kind":"tip","title":"Podsumowanie — Multi-Agent Networks","desc":"- Orchestrator dzieli pracę, specjaliści ją wykonują\n- Pliki .md jako system promptów — edytowalny bez dotykania kodu\n- Pipeline dla zadań liniowych, Blackboard dla równoległych\n- Zawsze: limit iteracji + logowanie każdego kroku"}]');

-- Lesson 5: DevOps w AI
INSERT INTO public.lessons (course_id, title, "order", duration)
VALUES (v_course_kod, 'DevOps w AI', 5, '12 min')
RETURNING id INTO v_lesson_id;

INSERT INTO public.slides (lesson_id, mode, "order", content_json) VALUES
(v_lesson_id, 'technical', 1, '[{"kind":"hero","text":"Nauczysz się jak utrzymać system AI przy życiu w produkcji — monitorować co robi, nie zbankrutować na tokenach i reagować zanim użytkownicy zaczną pisać do Ciebie złe maile."}]'),
(v_lesson_id, 'technical', 2, '[{"kind":"markdown","content":"## Scena 1 — Twoja aplikacja AI wyszła na produkcję. Co teraz?\n\nGratulacje! Twój agent działa. Użytkownicy go używają. I właśnie nie masz pojęcia co robi.\n\nKlasyczny błąd: traktujemy aplikację AI jak stronę statyczną — „wrzucam i zapominam". Tymczasem LLM to silnik z ruchomymi częściami: każde zapytanie kosztuje, może się zawiesić, zwrócić śmieci albo pożreć Twój budżet w 20 minut podczas stress testu.\n\n**DevOps w AI to nie opcja — to pas bezpieczeństwa.** I tak jak pas, zauważasz go dopiero gdy go nie masz."}]'),
(v_lesson_id, 'technical', 3, '[{"kind":"markdown","content":"## Scena 2 — Dashboardy: widzisz co się dzieje?\n\nMinimalne rzeczy które powinieneś mierzyć:\n\n- **Latencja** — ile czeka użytkownik na odpowiedź? Powyżej 5s zaczyna się frustracja.\n- **Liczba zapytań** — ile requestów na minutę? Na godzinę?\n- **Tokeny per request** — czy prompty są rozsądne?\n- **Błędy i timeouty** — jak często API nie odpowiada?\n- **Koszt** — ile wydajesz dziennie/tygodniowo/na użytkownika?\n\nNarzędzia: **LangSmith** (dla LangChain), **Langfuse** (open source, działa z każdym), **Helicone** (proxy do OpenAI/Anthropic z dashboardem).\n\nLangfuse szczególnie polecam — integruje się w 3 linie kodu i od razu widzisz każdy trace, token, koszt i latencję."}]'),
(v_lesson_id, 'technical', 4, '[{"kind":"markdown","content":"## Scena 3 — Rate limiting: ochrona przed tobą samym (i innymi)\n\nRate limiting to ograniczenie liczby zapytań w jednostce czasu. Potrzebujesz go z dwóch powodów:\n\n**Po stronie dostawcy API** masz limity narzucone z góry. Przekroczysz je → dostaniesz błąd 429. Bez obsługi tego błędu Twoja aplikacja się posypie.\n\n**Po swojej stronie** chcesz chronić się przed:\n- jednym użytkownikiem który robi 500 requestów na minutę\n- pętlą agenta która się zapętliła i woła API w nieskończoność\n- atakiem który kosztuje Cię prawdziwe pieniądze\n\nProsta implementacja: biblioteka `express-rate-limit` (Node.js) albo `slowapi` (Python). W n8n możesz dodać węzeł „Wait" między krokami. W architekturach agentowych: ustaw `max_iterations`."}]'),
(v_lesson_id, 'technical', 5, '[{"kind":"markdown","content":"## Scena 4 — Alerty: dowiedz się o problemie przed użytkownikiem\n\nUstaw powiadomienia gdy:\n- koszt dzienny przekroczy X zł\n- liczba błędów 5xx skoczy powyżej 5% requestów\n- latencja przekroczy 10 sekund\n- agent wykonał więcej niż 15 kroków (prawdopodobnie się zapętlił)\n\nNajprostsze rozwiązanie: **Langfuse** + webhooki do Slacka lub e-maila.\n\n**Złota zasada:** alert powinien być actionable — tzn. wiesz co zrobić gdy go dostaniesz. „Coś poszło nie tak" to nie alert, to szum."}]'),
(v_lesson_id, 'technical', 6, '[{"kind":"markdown","content":"## Scena 5 — Cache''owanie i ochrona przed kosztami\n\n**Cache''owanie promptów** — jeśli system prompt masz długi i stały (np. instrukcje dla agenta), możesz go cache''ować. Anthropic oferuje **Prompt Caching** — po pierwszym użyciu długi prompt jest cache''owany i kolejne requesty kosztują ~10× mniej. Oszczędność: 60–80% na powtarzających się zapytaniach.\n\n**Taktyki obniżania kosztów:**\n- Używaj mniejszych modeli do prostych zadań (klasyfikacja, ekstrakcja) — np. Haiku zamiast Opus\n- Ograniczaj `max_tokens` w odpowiedzi\n- Skróć kontekst — nie wkładaj do każdego requestu całej historii konwersacji\n- **Hard limit budżetu** — ustaw w kodzie maksymalny koszt per użytkownik/dzień"}]'),
(v_lesson_id, 'technical', 7, '[{"kind":"tip","title":"Podsumowanie — DevOps w AI","desc":"DevOps w AI to trzech przyjaciół: widzisz (dashboard), reagujesz (alerty), nie płacisz za głupoty (cache + rate limiting).\n\nBez tego budujesz samochód bez deski rozdzielczej — możesz nim jechać, ale nie wiesz ile masz paliwa ani czy silnik płonie.\n\nNarzędzia na start: Langfuse (monitoring) + express-rate-limit (ochrona) + Prompt Caching (koszty)."}]');

END $$;
